### ISSUE TITLE
Dependency incompatibility

### ISSUE THREAD

**Issue by mitramir55** [MIND-Lab/OCTIS#102]
* OCTIS version: octis 1.12.0
* Python version: 3.10.11
* Operating System: Linux (Colab notebook)

### Description

I'm trying to install Octis and import its modules.

### What I Did

First, I installed Octis with `pip install octis`. Then I see the following error in the installation process:

```
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.5 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
imbalanced-learn 0.10.1 requires scikit-learn>=1.0.2, but you have scikit-learn 0.24.2 which is incompatible.
Successfully installed scikit-learn-0.24.2
```

Afterwards, I have issues importing the `Coherence` module and I receive the following error:
`ImportError: numpy.core.multiarray failed to import`

I tried installing the two packages that cause the issue myself; however, I faced some other issues revolving around the version of Numpy and Python.

The issue happens when running the notebook you've provided as an example.

**Comment by tanstephenjireh** [comment]
Same issue
