### ISSUE TITLE
Python 3.12.1 pip Installation Error

### ISSUE THREAD

**Issue by AddisonDP** [MIND-Lab/OCTIS#118]
* OCTIS version: 1.13.1
* Python version: 3.12.1
* Operating System: Windows 10 LTSC

### Description

Attempted install using `pip install octis`. Passed through until reaching the scikit-learn dependency, wherein I got the below error message:

### What Happened

```
Collecting scikit-learn==1.1.0 (from octis)
  Using cached scikit-learn-1.1.0.tar.gz (6.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

Traceback lines....
File "C:\Users\MyLaptop\AppData\Local\Temp\pip-build-env-XXXXXXXX\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module> 
register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by silviatti** [comment]
Hi, it seems to be a problem with python 3.12. If you can downgrade it, it should solve it. Reference: https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

**Comment by AddisonDP** [comment]
Yfke's Pull Request fixed the issue completely for me when I used their repository.

**Comment by silviatti** [comment]
Okay, thanks :) I'll look into it soon. I'll close this issue then. Feel free to re-open if you have any related issues
