### ISSUE TITLE
Significance score per topics

### ISSUE THREAD

**Issue by inceatakan** [MIND-Lab/OCTIS#18]
* OCTIS version:
* Python version:
* Operating System:

### Description

I am working on topic modeling for noisy short texts, trying to get topic significance scores per topic.

### What I Did

```
for t in output: #'output' is the model itself 
    
    significance_uniform_score = topic_signif_uniform.score(t)
    print("Topic Significance Uniform Score: "+str(significance_uniform_score))
```
I get the following error message:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-67-3d2f7efb2b8f> in <module>
      1 # Retrieve metrics score
      2 
----> 3 for t in output[:]:
      4 
      5     #topic_diversity_score = topic_diversity.score(t)

TypeError: unhashable type: 'slice'

Is it possible to get topic significance score per topic?

**Comment by silviatti** [comment]
Hi!
I just added this feature for the kl-uniform (I think this is not possible for the other significance metrics) with the new release of OCTIS. You can update the library using `pip install -U octis`. Your code should look as something like this:

```python
model =  # define your model
model_output = model.train_model(dataset) 

topic_signif_uniform = KL_Uniform()
significance_uniform_score = topic_signif_uniform.score(model_output, per_topic=True)
```

The `per_topic` parameter allows the score method to return a list of values, corresponding to the values of the KL for each topic.

Silvia

**Comment by inceatakan** [comment]
It worked @silviatti ! Thank you very much.

-Atakan
