### ISSUE TITLE
Question: OCTIS supports GPU?

### ISSUE THREAD

**Issue by cidrugHug8** [MIND-Lab/OCTIS#19]
* OCTIS version: 1.8.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04.02

### Description

If I add a GPU with CUDA support, will OCTIS be faster?

### What I Did

```

```

**Comment by silviatti** [comment]
Hi!
OCTIS will go faster if you use neural topic models, i.e. [ProdLDA](https://github.com/MIND-Lab/OCTIS/blob/master/octis/models/ProdLDA.py), [NeuralLDA](https://github.com/MIND-Lab/OCTIS/blob/master/octis/models/NeuralLDA.py), [CTM](https://github.com/MIND-Lab/OCTIS/blob/master/octis/models/CTM.py), and [ETM](https://github.com/MIND-Lab/OCTIS/blob/master/octis/models/ETM.py). They are all implemented in pytorch. The other ones do not support the training on the GPU, so they will run on the CPU. 

Silvia

**Comment by cidrugHug8** [comment]
Thanks for the answer. I'll try the neural model!
