### ISSUE TITLE
Citation for NeuralLDA and ProdLDA

### ISSUE THREAD

**Issue by akashgit** [MIND-Lab/OCTIS#2]
Hi, thanks for sharing this amazing work!
I think the current citations for NeuralLDA and prodLDA is for the repo only. 
These models are from the Autoencoding Variational Inference for Topic Models (Srivastava and Sutton 2017) paper. please consider citing the paper as well. Thanks!

**Comment by silviatti** [comment]
Hello, 
I just fixed the readme with the correct citation. I'm going to add a direct link to the paper in the next few days. Thank you for reporting this!

Cheers,

Silvia

**Comment by akashgit** [comment]
Thank you very much Silvia! 
I've updated the official repo (which is quite outdated) (https://github.com/akashgit/autoencoding_vi_for_topic_models) to point OCTIS.

**Comment by silviatti** [comment]
Wow, thank you so much!!
