### ISSUE TITLE
NMF Model Cannot Be Imported Into Colab

### ISSUE THREAD

**Issue by gehcode** [MIND-Lab/OCTIS#22]
* OCTIS version: 1.8.0

### Description

Tried to import NMF model into Colab 

### What I Did

```
from octis.models.NMF import NMF
```
```
ImportError                               Traceback (most recent call last)
<ipython-input-17-96f0cef9c8fa> in <module>()
----> 1 from octis.models.NMF import NMF

/usr/local/lib/python3.7/dist-packages/octis/models/NMF.py in <module>()
      1 from octis.models.model import AbstractModel
      2 import numpy as np
----> 3 from gensim.models import nmf
      4 import gensim.corpora as corpora
      5 import octis.configuration.citations as citations

ImportError: cannot import name 'nmf' from 'gensim.models' (/usr/local/lib/python3.7/dist-packages/gensim/models/__init__.py)

```

**Comment by silviatti** [comment]
Hi!
I'll try to fix it as soon as possible. In the meantime, if you still want to use NMF, you can use the implementation that comes from scikit-learn: https://github.com/MIND-Lab/OCTIS/blob/master/octis/models/NMF_scikit.py

```python
from octis.models.NMF_scikit import NMF_scikit
model = NMF_scikit(...)
```

**Comment by silviatti** [comment]
It seems that the version of gensim installed on colab was the 3.6.0 that hadn't implemented NMF yet. I set the version of gensim in the requirements to a higher version and now it works. So now you can use either NMF or NMF_scikit :)
