### ISSUE TITLE
Can CTM return topic_significance_uniform score?

### ISSUE THREAD

**Issue by inceatakan** [MIND-Lab/OCTIS#23]
* OCTIS version:
* Python version:
* Operating System:

### Description

Currently, CTM returns only topic_significance_background score. Is it possible to get topic_significance_uniform score (per topic)?

Thanks,
-Atakan

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by silviatti** [comment]
Hi, what do you mean by "CTM returns only topic_significance_background score"? Can you show a code snippet? 
Once you get the model output, you can use it to compute every other evaluation metric that you like. For example:

```python
from octis.evaluation_metrics.significance_metrics import KL_uniform
from octis.evaluation_metrics.significance_metrics import KL_background

kl_u = KL_uniform() # Initialize metric
kl_b = KL_background() # Initialize metric

model = CTM(num_topics=25)  
model_output = model.train_model(dataset) 
kl_b_score = kl_b.score(model_output) # Compute KL-background score
kl_u_score = kl_u.score(model_output,per_topic=true) # Compute KL-uniform score
```

Hope this helped :)
