### ISSUE TITLE
Unexpected keyword argument 'df_max_freq' when max_features is used in Preprocessing

### ISSUE THREAD

**Issue by aneesha** [MIND-Lab/OCTIS#26]
Setting max_features in Preprocessing throws the following error:
TypeError: __init__() got an unexpected keyword argument 'df_max_freq'

Example code

```
import string
from octis.preprocessing.preprocessing import Preprocessing

# Initialize preprocessing
preprocessor = Preprocessing(vocabulary=None, max_features=None,
                             remove_punctuation=True, punctuation=string.punctuation,
                             lemmatize=True, stopword_list='english',
                             min_chars=1, min_words_docs=0, max_df=0.9, min_df=0.1) # 
# preprocess
dataset = preprocessor.preprocess_dataset(documents_path=r'dataset.csv')
```

I'm happy to help fix the issue. 

OCTIS is an excellent library - keep up the great work.

**Comment by silviatti** [comment]
Hi! 
Thank you for reporting the issue! I fixed it in the `dev branch`. I'd wait for the fix of the other issues you opened before creating the next release. 

Thanks again :)

Silvia
