### ISSUE TITLE
Hyperparameter Tuning of num_topics Errors

### ISSUE THREAD

**Issue by aneesha** [MIND-Lab/OCTIS#28]
I get the following error when trying to do hyperparameter optimation on num_topics:

/usr/local/lib/python3.7/dist-packages/octis/models/contextualized_topic_models/models/ctm.py in __init__(self, input_size, bert_input_size, inference_type, num_topics, model_type, hidden_sizes, activation, dropout, learn_priors, batch_size, lr, momentum, solver, num_epochs, num_samples, reduce_on_plateau, topic_prior_mean, topic_prior_variance, num_data_loader_workers)
     45             "input_size must by type int > 0."
     46         assert isinstance(num_topics, int) and input_size > 0, \
---> 47             "num_topics must by type int > 0."
     48         assert model_type in ['LDA', 'prodLDA'], \
     49             "model must be 'LDA' or 'prodLDA'."

AssertionError: num_topics must by type int > 0.

### What I Did

```
ctm_model = CTM(model_type='prodLDA', bert_model="stsb-roberta-base-v2", inference_type="combined")

search_space = {"num_topics": Integer(5, 10, 15, 20),
                "num_layers": Categorical({1, 2, 3}), 
                "num_neurons": Categorical({100, 200})
}

optimization_runs=20
model_runs=1

optimizer=Optimizer()
optimization_result = optimizer.optimize(
    ctm_model, dataset, npmi, search_space, number_of_call=optimization_runs, 
    model_runs=model_runs, save_models=True, 
    extra_metrics=None, # to keep track of other metrics
    save_path='results/test_ctm/')

optimization_result.save_to_csv("results_ctm.csv")

```
Happy to assist with fixing this issue.

**Comment by silviatti** [comment]
Hi, 
I should have fixed the bug in the dev branch. Let me know,

Silvia

**Comment by silviatti** [comment]
I have just released a new version of OCTIS that handles this problem (v 1.9.0). You can run `pip install -U octis` to download the latest version. Feel free to reopen the issue if you still have problems. 

Silvia
