### ISSUE TITLE
Control of prior distribution

### ISSUE THREAD

**Issue by ogencoglu** [MIND-Lab/OCTIS#3]
If you are doing Bayesian optimization, it is probably a good idea to give the control of prior probability distribution to the user. Any plans to add that to your API?

**Comment by brunoG89** [comment]
Hi, thank you for your interest.
For the Bayesian Optimization part, we rely on the scikit-optimize library. The ways to control the prior over BO are the following:

1. use different surrogate models, i.e. Gaussian Process and Random Forest, and this can be specified both in the python library and from the dashboard

2.  choose a specific kernel for the Gaussian Process (this feature is available only in the python library at the moment). The default kernel is 1.0 * Matern(length_scale=1.0, length_scale_bounds=(1e-1, 10.0), nu=1.5), but you can pass any other kernel from sklearn (See "sklearn.gaussian_process.kernels" here: https://scikit-learn.org/stable/modules/classes.html).

**Comment by ogencoglu** [comment]
Thanks for the prompt reply! 

I now see that control on surrogate model is possible. What I also meant is for example in hyperparameter optimization, one usually want to be able to control the distribution (_normal_, _log-normal_, _uniform_, _log-uniform_ etc.) to sample from for each hyperparam separately. `skopt.space` classes (e.g. `Real`, `Integer`) has some control on this if I remember correctly.

**Comment by brunoG89** [comment]
Hi,
yes, skopt.space allows you to specify a prior over the numeric hyperparameters. The possible values are "uniform" and "log-uniform".
Thanks for your questions, we are going to make this clearer in the OCTIS documentation.
Cheers,
Bruno
