### ISSUE TITLE
ETM - Possibility of using KeyedVectors input for pre-trained W2V embeddings

### ISSUE THREAD

**Issue by lffloyd** [MIND-Lab/OCTIS#32]
* OCTIS version: 1.9.0
* Python version: 3.7.6
* Operating System: Ubuntu 20.04 LTS

### Description

Hi, this is more of a question than anything else. I've seen that for ETM model training, we must pass an embeddings path corresponding to a "pickled" file. However, I need to execute ETM with rather large embeddings. There's any intent on implementing a [```gensim.models.KeyedVectors```](https://radimrehurek.com/gensim/models/keyedvectors.html) based (or something like that) embeddings input for this model? I've implemented something like that for [an etm package of mine](https://github.com/lffloyd/embedded-topic-model/blob/bea451a28f32cdfcb47bc5fabd9efd9a0ecba2c8/embedded_topic_model/models/etm.py#L161), but yours' has all I need to execute model optimization. Would a PR on this matter be accepted?

Anyway, cheers for the nice work, this package is really great!

### What I Did

Gave a look at [here](https://github.com/MIND-Lab/OCTIS/blob/69988cae2c9e9b0db75a28cda4784f0101069cc5/octis/models/ETM.py#L345).

**Comment by silviatti** [comment]
Hi! Glad you like our work :)  

I think using gensim's KeyedVectors for ETM can be useful. As you've seen [here](https://github.com/MIND-Lab/OCTIS/blob/69988cae2c9e9b0db75a28cda4784f0101069cc5/octis/models/ETM.py#L365), I've also started from embeddings in word2vec format and then filtered and converted them into a pickle file. 

I would allow the user to use either pickle or word2vec (like in gensim) format. I would definitely accept a PR on this. 

Silvia

**Comment by lffloyd** [comment]
Hello again, @silviatti. I opened a PR (#36) addressing this topic. The same PR fixes a bug which I encountered, described on #37.

**Comment by cayaluke** [comment]
Hello @lffloyd and @silviatti 

This question is related to issue #38.

With regards to PR #36 can either of you confirm if the pre-trained embedding file that Dieng provides for her ETM and DETM models will work after the pull request is merged and OCTIS is updated? The file is called "skipgram_emb_300d.txt". Here is the bitbucket location for your reference https://bitbucket.org/diengadji/embeddings/src/master/.

Thank you 
Luke

**Comment by lffloyd** [comment]
Hi, @cayaluke. I've added [a commit](https://github.com/MIND-Lab/OCTIS/pull/36/commits/086d7ebe6aace2908295b1488580b5e47809f141) to PR #36 providing support for headerless word2vec embeddings, like the ones you've linked. Previously, my code only supported word2vec embeddings with a header line in the format ```<no_of_vectors_in_the_file> <vector_length>```.

After the PR merging, you will be able to load Dieng's embeddings like this:
```python
model = ETM(num_topics=5, num_epochs=5, train_embeddings=False, 
        embeddings_type='word2vec', embeddings_path='your_folder/skipgram_emb_300d.txt', 
        binary_embeddings=False, headerless_embeddings=True)
```

**Comment by cayaluke** [comment]
@lffloyd Thank you for your response. It is much appreciated.

**Comment by cayaluke** [comment]
Hello @silviatti and @lffloyd 

Can I please check if the PR #36 merge has been completed?
Thank you kindly for your assistance.
Luke

**Comment by silviatti** [comment]
Hi, I merged the PR on the branch `dev_etm`. Now I'm going to fix another issue and make the new release. It should be available in the next few hours. Thank you for your patience :)

**Comment by cayaluke** [comment]
@silviatti thank you! :)
