### ISSUE TITLE
ETM - How to use pretrained word embeddings

### ISSUE THREAD

**Issue by cayaluke** [MIND-Lab/OCTIS#38]
@silviatti Hello again,

I have another silly question for you.

The original ETM package allows the user to use pre-trained word embeddings (the file name is 'skipgram_emb_300d.txt')

How do I tell the model to look for the pretrained embedding file instead?

Is it something like:

model = ETM(num_topics=25, embeddings_path = '...\path\to\embeddings\'skipgram_emb_300d.txt'') ?

Thank you again for your assistance :)

Luke

**Comment by silviatti** [comment]
Hi Luke, 
yes, you have to set the parameter "train_embeddings" to False and set the parameter "embeddings_path" to the path of the pre-trained embeddings. Now we support the only embeddings in the word2vec format, but after PR #36 we will also support pre-trained embeddings in gensim's KeyedVector format. 

Code example:

```python
model = ETM(num_topics=25, train_embeddings=False, embeddings_path = '.../path/to/embeddings/skipgram_emb_300d.txt') 
```

Silvia

**Comment by cayaluke** [comment]
Thank you a million!
