### ISSUE TITLE
"Select Path" button bug in "Create Experiments" tab

### ISSUE THREAD

**Issue by thiagosmpa** [MIND-Lab/OCTIS#54]
* Python version: 3.9
* Operating System: MacOS

- Description

In the dashboard, I was trying to create an experiment. Everything was ok, but got an error when I clicked to "Select Path" to where to save the experiments.

I got the error:

RuntimeError: main thread is not in main loop

<img width="1440" alt="Captura de Tela 2022-02-22 às 17 04 03" src="https://user-images.githubusercontent.com/33949962/155181791-eebf44b3-7d57-4d7d-a7ff-c52c9d6bca2e.png">
<img width="1440" alt="Captura de Tela 2022-02-22 às 17 03 55" src="https://user-images.githubusercontent.com/33949962/155181807-f225f116-7c7e-418e-accb-d44593d4381f.png">

**Comment by pietrotrope** [comment]
Hi!
To choose the folder using a GUI we use tkinter, and according to:
https://www.python.org/download/mac/tcltk/
it is currently possible to see problems to file open and save dialogs using tkinter on macOS.

I tried to reproduce the error on Ubuntu and I was unable to get it.

If you are interested you could try to follow the instructions on the link and let us know if it works or if we need to investigate the problem further.

Pietro
