### ISSUE TITLE
cannot fetch dataset

### ISSUE THREAD

**Issue by dkorenci** [MIND-Lab/OCTIS#59]
Hello,

Dataset.fetch_dataset() leads to an error, due to lines 71-73 in octis/dataset/downloader.py
returning [404] responses. Root Dataset URL (line 69) seems incorrect.
Manual fetching through a browser also leads to 404. 
downloader.py current version is the same as the local version in octis 1.10.0

thank you, Damir

* OCTIS version: 1.10.0
* Python version: 3.9.4
* Operating System: Ubuntu 20.04

**Comment by silviatti** [comment]
Hello Damir, 
sorry for the late answer. Can you please tell me the name of the dataset you were downloading? The argument of the method `dataset.fetch_dataset()` is the name of the dataset as a string. You can find the list of the names here: https://github.com/MIND-Lab/OCTIS/#available-datasets  

For example: 
```python
dataset = Dataset()
dataset.fetch_dataset("20NewsGroup")

```

Thanks,

Silvia

**Comment by silviatti** [comment]
Hello,
it was a spelling mistake. Now it should work. Let me know if you have other issues.

Silvia

**Comment by dkorenci** [comment]
Hello, it works, thank you. 

Damir
