### ISSUE TITLE
Not able to run dashboard

### ISSUE THREAD

**Issue by rsreetech** [MIND-Lab/OCTIS#8]
* Python version: 3.6
* Operating System: Windows 

### Description

I tried:
python  octis\dashboard\server.py

and i get this error:

import octis.dashboard.experimentManager as expManager
AttributeError: module 'octis' has no attribute 'dashboard'

**Comment by pietrotrope** [comment]
Hello rsreetech, thanks for using OCTIS and reporting this error!

I've fixed the error and it shouldn't occur anymore.
Let me know if it works.

Best,

Pietro

**Comment by rsreetech** [comment]
Still get same error

**Comment by pietrotrope** [comment]
I solved the problem, now a pull should be enough :)
If the problem persists can you send us a complete report of the error?
Thank you!

**Comment by rsreetech** [comment]
Works Now. Thanks!!
