### ISSUE TITLE
Evaluating a custom topic model

### ISSUE THREAD

**Issue by nfsedaghat** [MIND-Lab/OCTIS#81]
Is there any ways to use your package for evaluating a custom topic model? What outputs in what formats I should get from my model and use to compute the metrics?

**Comment by silviatti** [comment]
Hello :)
yes, it is possible to evaluate  an external topic model using OCTIS metrics. You can refer to this issue for more details on how to do it and for the format to use: https://github.com/MIND-Lab/OCTIS/issues/61
Feel free to re-open the issue if you have further questions :)

Silvia
