### ISSUE TITLE
Is it okay to use OCTIS to evaluate topic models from other Python modules?

### ISSUE THREAD

**Issue by Zay-Ben** [MIND-Lab/OCTIS#85]
Let's say:

Z - the number of topics
W - the number of words (unique)
D - the number of documents

Given that OCTIS returns a dictionary containing a "topic-word-matrix" (a Z by W matrix), a list of "topics" (the top words for each topic), a "topic-document-matrix" (a Z by D matrix), and a "test-topic-document-matrix" (which can be initialized as a NumPy array containing an empty list), is it possible to convert the output of a topic model from another module into a similar format as the output of OCTIS in order to evaluate the topic model's performance using different metrics in OCTIS?

Thank you! :)

**Comment by silviatti** [comment]
Hello :)
yes, you can evaluate the output of an external topic model using OCTIS metrics. You can refer to this issue for more details on how to do it: https://github.com/MIND-Lab/OCTIS/issues/61
Feel free to re-open the issue if you have further questions :)

Silvia
