### ISSUE TITLE
ValueError in colab notebook

### ISSUE THREAD

**Issue by amrzv** [MIND-Lab/OCTIS#87]
* OCTIS version: 1.11.0
* Python version: 3.8.16
* Operating System: default colab env
* numpy version: 1.21.6
* gensim version: 4.3.0

### Description
When running `OCTIS: Optimizing CTM.ipynb` notebook in colab there raised `ValueError` at the very beginning of the notebook during imports.

### What I Did
Kernel -> Run all cells
![image](https://user-images.githubusercontent.com/36787333/212035062-16041fc0-29e8-42f6-87e4-ecde0c2d50a1.png)
`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

Seems like there is an incompatibility between gensim and numpy packages.
"Restart kernel and run all" doesn't help.

**Comment by ericchagnon15** [comment]
Have you found a fix for this?

**Comment by amrzv** [comment]
Yes, with the latest gensim release 4.3.0, there raises `ValueError`, as shown above, but it works with 4.2.0:
`!pip install octis gensim==4.2.0`

Maybe the requirements should be changed.
