### ISSUE TITLE
Not able to run ProdLDA

### ISSUE THREAD

**Issue by rsreetech** [MIND-Lab/OCTIS#9]
* Python version: 3.6
* Operating System: Windows 

### Description

I tried:
from octis.models.ProdLDA import ProdLDA

and get the following error:
d:\octisexp\lib\site-packages\octis\models\pytorchavitm\__init__.py in <module>
      1 """Init package"""
      2 
----> 3 from octis.models.pytorchavitm.avitm.avitm_model import AVITM_model

ModuleNotFoundError: No module named 'octis.models.pytorchavitm.avitm'

I have created a virtual environment and installed octis using : pip install octis

**Comment by silviatti** [comment]
Hi! 
Thanks for reporting! :) There was a missing __init__.py file. We have solved this issue with the release of version 1.3.0. 
Bye,

Silvia
