### ISSUE TITLE
Can you tell how the datasets are preprocessed?

### ISSUE THREAD

**Issue by ERijck** [MIND-Lab/OCTIS#93]
Hi, is it possible to share the preprocessing settings steps for each dataset? E.g. What was the threshold for removing frequent/infrequent words?

**Comment by silviatti** [comment]
Hi, 
each dataset folder contains a "metadata.json" file, with the preprocessing details (see the field `preprocessing-info`). For example [BBC news dataset](https://github.com/MIND-Lab/OCTIS/blob/master/preprocessed_datasets/BBC_News/metadata.json).
As far as I remember, we selected those values by iteratively trying different values and inspecting the resulting topics.

**Comment by ERijck** [comment]
Thanks, Silviatti!
